name: Push Master CI Flow

on:
  push:
    branches:
      - 'master'

jobs:
  Test:
    name: Run Tests
    runs-on: macOS-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    - name: List Versions of Xcode
      run: ls /Applications | grep Xcode
    - name: List Simulator Versions
      run: xcrun simctl list
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.6_beta.app
    - name: Show Selected Xcode Version
      run: /usr/bin/xcodebuild -version
    - name: Xcode Test
      run: xcodebuild clean test -scheme GitActionsTDD_BLENFC -project GitActionsTDD_BLENFC.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.6'

  Build:
    needs: Test
    name: Build
    runs-on: macOS-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.6_beta.app
    - name: Xcode Build and Archive
      run: |
        xcodebuild clean build -scheme GitActionsTDD_BLENFC -project GitActionsTDD_BLENFC.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.6' \
        archive -allowProvisioningUpdates -archivePath GitActionsTDD_BLENFC.archive
    - name: Export Archive
      run: |
        xcodebuild -exportArchive \
        -allowProvisioningUpdates \
        -exportOptionsPlist GitActionsTDD_BLENFC/exportOptions.plist \
        -archivePath GitActionsTDD_BLENFC.archive \
        -exportPath GitActionsTDD_BLENFC.ipa
    - name: Save Artifect
      uses: actions/upload-artifact@v1
      with:
        name: GitActionsTDD_BLENFC.ipa
        path: build/


    
